window.SUPABASE_URL = 'https://iiherfubfpjxgttviqdm.supabase.co';
window.SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlpaGVyZnViZnBqeGd0dHZpcWRtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ5ODQ0NDUsImV4cCI6MjA5MDU2MDQ0NX0.t14eGIm3HgZPyfs5NtiqovtQADwKYjPNd7iX9AgYTWs';
